#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Shimono Mao <simonomao1535@gmail.com>
# SPDX-License-Identifier: This Softwere Package allowed Redistribution and Use by GPL 3.0
import sys

x = 0
err = 0
for line in sys.stdin:
    if 'f' in line: 
        break
    try:
        x += int(line)
    except ValueError:
        print("ERROR!!!")
        err = 1
        break
    except:
        x += float(line)
if err == 1:
    exit()
else:
    print(x)
    exit()

